org: hyungju
app: vacgom-codef-api
service: vacgom-codef-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  api:
    handler: src/index.handler
    timeout: 10
    events:
      - httpApi: '*'

resources:
  Resources:
    requestTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: requestTokensTable
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true
    credentialsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: credentialsTable
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  serverless-dynamodb:
    start:
      seed: true
      migrate: true

    seed:
      credentialsTable:
        sources:
          - table: credentialsTable
            sources: [ ./credentialsTable.json ]
